### PR TITLE
replace http-response helper with request and rsvp

### PR DESCRIPTION
**Pull request by ahaurw01**
Feel free to impose whatever coding style you like. Also when you get the chance can you add me as a contributor?

### CODE REVIEW

**Comment by SirZach** [comment]
I like that code style :) I was thinking about adding promises in. You're now a collaborator, thanks a lot for the PRs! I think the two PRs conflicted with each other though so this one can't be merged in at the moment. Would you mind resolving the conflict?

**Comment by ahaurw01** [comment]
No sweat. :sweat_smile:

**Comment by SirZach** [comment]
it's kind of silly exciting to do a git pull on an open source project

**Comment by ahaurw01** [comment]
I know that feeling :smiley:

**Pull request merged**
