### PR TITLE
set user agent for http requests

### PR DESCRIPTION
**Pull request by ahaurw01**
Looks like images are busted. Requests made during the image route handling were failing until a user agent was set. Go figure.

### CODE REVIEW

**Comment by ahaurw01** [comment]
FYI, I'm going to merge to hopefully get things working again in production.

**Comment by ahaurw01** [comment]
Looks like it did the trick. ¯\_(ツ)_/¯

**Comment by SirZach** [comment]
Just noticed this last night. Don't know how you figured that out but thank you!

**Comment by ahaurw01** [comment]
Sure thingy. I was wondering first if our domain was blocked, but localhost had the same problem, so I wondered if the user agent was blocked. Then I realized that no user agent was being sent and if I curled specifically with `-H "User-Agent: "` I got the same error that occurred at runtime. Who knows what's going on over there...

**Comment by SirZach** [comment]
should we start building up a library of these images ourselves?

**Comment by ahaurw01** [comment]
Not a bad idea. This is a pretty crazy solution. It's too bad that mtgimages service got killed.

**Comment by SirZach** [comment]
yeah, it is only by luck that we (you) managed to find another site to get images from. wanna have a date and chat about it?

**Comment by ahaurw01** [comment]
:+1: :+1: I'm unfortunately out of town next week, but free after that!

**Comment by SirZach** [comment]
next week won't be good for me either but the following week has boat loads
of potential!

**Pull request merged**
